### ISSUE TITLE
Non-exported error type

### ISSUE THREAD

**Issue by PaulAvery** [zkat/cacache-rs#23]
Hi Kat,

I am currently trying to use your library in a project of mine and kinda tripped over error-handling in the crates documentation. Because the `Error` struct exposed (and documented) by the crate is not actually used in any of the crates return types, it became somewhat unclear to me, what the preferred approach to error handling with your crate is.
Also, the `anyhow` error type is not exposed by your crate directly, so if someone wants to wrap the error themselves they would have to add an additional dependency to anyhow.

I would love to send a pull request to fix this issue, though I am not sure what the right approach would be. If you consider this purely a documentation issue I will gladly change the ReadMe and add a paragraph to the error enums documentation.

Oh and thank you for your work, on this library and in general.
Greetings,

Florian

**Comment by zkat** [comment]
Hi! Thanks for the lovely, thoughtful issue! I'm honestly fairly new to Rust and haven't gotten used to how error patterns are supposed to written.

My first thought is that this should re-export `anyhow::Error` to start.

Or maybe the expected pattern is to have users just expect `impl std::error::Error`? What would work best for you, since you're an actual user? I don't mind making breaking changes!

**Comment by PaulAvery** [comment]
Thanks for your quick response. I am also new to Rust and currently in the exactly same boat as you in regards to error handling.

For my current use case I just need the ability to wrap cacaches errors and an exposed anyhow error would solve that issue nicely. I am not sure if tying your major version to that of anyhow is worth it though.
Consumers would also have no ability to distinguish between error types (I guess `EntryNotFound` might be very useful e.g.).

What I have seen in other library crates is to expose an error enum with specific, relevant members and wrap any underlying errors inside of it (which I think was your original approach).
The big tradeoff seems to be being able to treat all errors the same and therefore being able to easily add context vs. clearly communicating error states to the outside world. The author of the `thiserror` and `anyhow` crates apparently draws the line between "application" and library crates: https://github.com/dtolnay/anyhow#comparison-to-thiserror

In my own code I would probably resort to using a backtrace (which thiserror can attach automatically) to figure out the callchain and wrap errors of underlying libraries manually. And if additional context for an error type is important, add an additional entry to the error enum.
I am not sure how important custom error context is to you. If you don't mind replacing it with a backtrace for the general case, I would attempt the above approach in a PR to see how it feels.

**Comment by zkat** [comment]
closed by #24 :)
