### ISSUE TITLE
tests: more coverage

### ISSUE THREAD

**Issue by zkat** [zkat/cacache-rs#3]
There's a terrifying lack of test coverage on cacache right now. There should be unit tests for at least all the API functions, and preferably also for the internal APIs.

**Comment by rickycodes** [comment]
I'd love to work on this! already added a quick test for `cacache::rm::all`. would be open to discuss how you'd want to structure this in a PR :)

**Comment by zkat** [comment]
You can dump a big fat PR or several smaller PRs! Whatever is most convenient to you. Thanks for picking this up! Also, make sure you're ok with [the license](https://github.com/zkat/cacache-rs/blob/latest/LICENSE.md) (I call this out because I **just** changed the license and I know it's an unusual licensing setup. I don't want contributors to be surprised!)

Let me know if you need any help! :)

**Comment by zkat** [comment]
A bunch more coverage has been added. There's a few gaps here and there but we can tackle that in a more focused way. Thanks for your help with this, @rickycodes!
