### ISSUE TITLE
Consider revising the repository's about description

### ISSUE THREAD

**Issue by philpax** [zkat/cacache-rs#44]
Heya! This just came across my GitHub following feed and it looks really interesting, but I must admit I almost ignored it at first because of the about description:

>  💩💵 but for your 🦀 

It's fun, but it's not particularly informative (and honestly, it sounded like a shitpost-as-repo). I'm glad I checked it out, though, because

> A high-performance, concurrent, content-addressable disk cache, optimized for async APIs.

is *much* more interesting as a driveby viewer!

Apologies if it sounds like I'm telling you how to run your repo - I just don't want other people to make the same mistake I almost did 😅

**Comment by zkat** [comment]
I was thinking the same thing recently, tbh.

Fixed. What do you think? :)

**Comment by philpax** [comment]
Perfect :D
