### ISSUE TITLE
Related lib reflink has important fix merged but seems it's not going to be released

### ISSUE THREAD

**Issue by shandak** [zkat/cacache-rs#46]
The related lib reflink is quite old and has a bug described there https://github.com/nicokoch/reflink/issues/4 so the same issue happens when I'm using cacache too. Would not be a problem for you to bump dependency like there https://github.com/bczhc/rust/commit/e9df2babbabf20588c891f55af113d46293441ea  to the master branch?

**Comment by zkat** [comment]
unfortunately, I can't publish git dependencies to crates.io, so the only way I would be able to do this is if a "forked" version of reflink with the patch applied were published to crates.io, or the original author actually releasing a new version.

**Comment by shandak** [comment]
I did a fix like that in `Cargo.toml`
```
[replace]
ttps://github.com/nicokoch/reflink/issues/4
"reflink:0.1.3" = { git = "https://github.com/nicokoch/reflink", rev = "e8d93b46" }
```

**Comment by jakubadamw** [comment]
I'd honestly reconsider depending on that package. It's not being maintained.

**Comment by zkat** [comment]
I'd like to keep this open, since it's definitely still an issue.

I'd love to get rid of this as a dependency, but `reflink` is a pretty nontrivial package, and I want access to the functionality it's providing.

**Comment by 06chaynes** [comment]
It looks like there is a maintained fork here: 
https://github.com/cargo-bins/reflink-copy
https://crates.io/crates/reflink-copy
