### ISSUE TITLE
Deadlock when accessing across two threads.

### ISSUE THREAD

**Issue by j-mendez** [zkat/cacache-rs#73]
Hi, we are using the crate through [reqwest-cache](https://github.com/06chaynes/http-cache/tree/main/http-cache-reqwest). The crate seems to perform the standard read operation found [here](https://github.com/06chaynes/http-cache/blob/main/http-cache/src/managers/cacache.rs). I have an example of the cache reading here that works in the manner the code is written because of the select and pin https://github.com/spider-rs/spider/blob/main/examples/cache.rs. If we change the code to remove the select and spawn tasks instead the subscription will hang forever. 

I could post the deadlock here in a code example if needed.

**Comment by j-mendez** [comment]
Nvm, found the deadlock was elsewhere sorry about that!

**Comment by zkat** [comment]
No worries. cacache is completely lockless, so you shouldn't get stuff like deadlocks!
