### ISSUE TITLE
reading from a cacache::WriteOpts Writer, before its completed

### ISSUE THREAD

**Issue by cablehead** [zkat/cacache-rs#77]
I'm investigating allowing content to be streamed out of a CAS store, while it's still being ingested.

The rough idea I have is to be able to get a Reader for an open Writer, which reads from the tmpfile, that then somehow switches to the canonical version of the content, once the Writer is closed, and the content hash is known.

This may be a terrible idea 😅

If it did sound reasonable though, I'd be interested in helping to contribute the feature.

**Comment by zkat** [comment]
@cablehead what you're looking for is called a "tee", or "tee stream". https://docs.rs/io_tee/latest/io_tee/ implements it for regular `Read`s, but you can look around and see if you find one that works for `AsyncRead`.

**Comment by cablehead** [comment]
Hi Kat! Right, my first thought was a "tee" too. A potential issue with a tee for my [use case](https://github.com/cablehead/xs), is it's not clear at the start of ingest who will be interested in the content immediately. And it could be noone. If I always open up a tee, with no readers to consume it, the tee could end up slurping the full content into memory (depending on how it's structured), for no reason.

So that got me thinking, what if early readers were given a handle to the [tempfile](https://github.com/zkat/cacache-rs/blob/main/src/content/write.rs#L63) and they read directly from there? I need to dig into how [tempfile::NamedTempFile.persist](https://docs.rs/tempfile/latest/tempfile/struct.NamedTempFile.html#method.persist) works, but if it preserves the inode, early readers can continue to consume the content, even as the write ingest completes and the content is moved to its canonical position.

**Comment by cablehead** [comment]
Actually, for my use case, I think I've been overthinking this 😅. It'd be simpler to emit events as chunks of content become available rather than using a complicated tee strategy.
