### ISSUE TITLE
Lockless? 

### ISSUE THREAD

**Issue by j-mendez** [zkat/cacache-rs#86]
Hi I noticed the crate says it is lockless but, I see a Mutex being used for polling. This would be against the lockless design entirely. We might want to update the crate technicals for this.

**Comment by zkat** [comment]
"Lockless" in this case refers to preventing multiple processes or threads from accessing the cache. This is still the case: you can just as easily create multiple AsyncWriters that write to the exact same hash, and cacache will be fine. The Mutex is to prevent memory corruption on a _single_ writer.

Typically, caches and databases require that you hold some kind of lock on the entire database, or at least the destination key that you're trying to write to. cacache has no such requirement.

**Comment by j-mendez** [comment]
> "Lockless" in this case refers to preventing multiple processes or threads from accessing the cache. This is still the case: you can just as easily create multiple AsyncWriters that write to the exact same hash, and cacache will be fine. The Mutex is to prevent memory corruption on a _single_ writer.
> 
> Typically, caches and databases require that you hold some kind of lock on the entire database, or at least the destination key that you're trying to write to. cacache has no such requirement.

Thanks for the answer :)
